### ISSUE TITLE
refactor de rutas del proyecto

### ISSUE THREAD

**Issue by hamletSolanoD** [Productivity-Plus/Productivity-Plus-HREngine#36]

**Comment by hamletSolanoD** [comment]
Una vez agregada las nuevas entidades corregir las rutas creadas previamente para que ahora todas unicamente hagan referencia al objeto User o los objetos del modulo.
Eliminar las redundancias de la primer beta

**Comment by pro-plus-mx** [comment]
todas las rutas estan estandarizadas a: Add, Edit, Delete y Get, expecto las especiales como workday que es in y out, ademas de activities start y end y los candidatos y que tiene especiales como fill y status, registrer.
